### UserController::createNewUser
POST http://localhost:9091/api/v1/users
Content-Type: application/json

{
  "name":"Sazib Khan",
  "email":"Software Engineer",
  "mobile":"01717226385",
  "gender":"Male",
  "age":18,
  "nationality":"Bangladesh"
}




